export const ROUTES = Object.freeze({
  LOGIN: '/login',
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_TASKS_CREATE: '/admin/tasks/create',
  ADMIN_TASK_BOARD: '/admin/tasks',
  ADMIN_TASK_DETAIL: '/admin/tasks/:taskId',
  ADMIN_STAFF: '/admin/staff',
  ADMIN_SCHEDULE: '/admin/schedule',
  ADMIN_BROADCAST: '/admin/broadcast',
  ADMIN_BROADCAST_CREATE: '/admin/broadcast/create',
  ADMIN_BROADCAST_DETAIL: '/admin/broadcast/:noticeId',
  ADMIN_BROADCAST_EDIT: '/admin/broadcast/:noticeId/edit',
  PRIVATE_NOTES: '/notes',
  STAFF_DASHBOARD: '/staff/dashboard',
  STAFF_TASKS_CREATE: '/staff/tasks/create',
  STAFF_TASK_BOARD: '/staff/tasks',
  STAFF_TASK_DETAIL: '/staff/tasks/:taskId',
  STAFF_PROFILE: '/staff/profile',
  UNAUTHORIZED: '/unauthorized',
  NOT_FOUND: '/404',
})
